### ISSUE TITLE
Editable Poster Link

### ISSUE THREAD

**Issue by euhidaman** [microsoft/workshop-template#3]
The [Canva Poster Link](https://www.canva.com/design/DAEuDXXR9us/share/preview?token=Je0_213uqxmYaXnNYz1v-Q&role=EDITOR&utm_content=DAEuDXXR9us&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton) shared in this repository, is editable by anyone.
This may lead to problems, as anyone not experienced with Canva, may edit the main poster itself.

To fix the problem, share the link of the poster as a template.
![correct](https://user-images.githubusercontent.com/65843257/152392406-0cb6b92f-4338-4a65-a5f6-19b405ec80ca.png)

**Comment by jlooper** [comment]
smart! done!
